Repository canonical/jenkins-agent-operator, pull requests merged in 2024-01, with the labels that each got.

#6 Add docs to metadata for gatekeeper
  charmcraft.yaml
  config.yaml
  generate-src-docs.sh
  metadata.yaml
  src/charm.py
  tests/conftest.py
  tests/integration/__init__.py
  tests/integration/test_charm.py
  tests/unit/__init__.py
  tests/unit/test_base.py
  tox.ini
Labels: trivial

#8 update readme
  README.md
  docs/index.md
Labels: Libraries: Out of sync, trivial

#10 enable 2-way sync with gatekeeper
  .github/workflows/promote_charm.yaml
Labels: Libraries: Out of sync, trivial

#14 pin apt package version to 1.0.4
  src/service.py
Labels: Libraries: OK, trivial

#19 Create bot_pr_approval.yaml
  .github/workflows/bot_pr_approval.yaml
Labels: Libraries: OK, trivial

#17 ISD-1514 Add unit tests, set coverage target to 95
  pyproject.toml
  tests/unit/conftest.py
  tests/unit/test_agent.py
  tests/unit/test_charm.py
  tests/unit/test_service.py
  tests/unit/test_state.py
Labels: Libraries: OK, complex
